version: '3'
services:
  flask:
    restart: always
    build: .
    command: python3 root.py
    container_name: 'flask'
    tty: true
    volumes:
      - ./src/flask:/root/src
    ports:
      - "8000:5000"
      
  sreamlit:
    build: ./src/streamlit
    command: python3 app.py
    container_name: streamlit
    tty: true
    volumes:
      - ./src/streamlit:/root/src
    ports:
      - "8001:5000"