version: '3'
services:
  flask:
    restart: always
    build: .
    command: python3 root.py
    container_name: 'flask'
    tty: true
    volumes:
      - ./src/flask:/root/src
    ports:
      - "8000:5000"